# This is a basic workflow to help you get started with Actions

name: Publish Static Serializer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout aaubry/yamldotnet
        id: yamldotnet
        uses: actions/checkout@v3
        with:
          repository: aaubry/yamldotnet
          ref: master
          fetch-depth: 0
          path: yamldotnet
          submodules: 'true'

      - name: Get current version
        id: version
        working-directory: yamldotnet
        run: |
          $VERSION=(git tag -l --sort=-v:refname v*)[0].Replace("v", "")
          write-host "Using $VERSION"
          "PACKAGE_VERSION=$VERSION" | Add-Content $GITHUB_ENV

      - name: Install dotnet 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Install dotnet 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install dotnet 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        id: build
        working-directory: yamldotnet
        run: dotnet build -c Release YamlDotNet.sln

      - name: Test
        id: test
        working-directory: yamldotnet
        run: dotnet test -c Release --no-build YamlDotNet.sln

      - name: Pack
        id: pack
        working-directory: yamldotnet/YamlDotNet.Analyzers.StaticGenerator
        run: dotnet pack YamlDotNet.Analyzers.StaticGenerator.csproj \
          -o ${GITHUB_WORKSPACE}/packed \
          -p:NuspecFile=${GITHUB_WORKSPACE}/YamlDotNet.Analyzers.StaticGenerator.nuspec \
          -p:Version=${PACKAGE_VERSION}

      - name: Debug1
        id: debug1
        run: printenv && ls ${GITHUB_WORKSPACE}/packed
